name: node-test
on:
  repository_dispatch:
  push:
   branches:
   - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.19.0]
    
    steps:
     - name: My first action
       env:
        GITHUB_TOKEN: ${{ secrets.address }}
        HOST: Mona
        key: Octoca
               
     - name: Checkout repository
       uses: actions/checkout@v2
       
     - name: Set up Node.js
       uses: actions/setup-node@v2
     - run: node hello.js
        

      # 在这里添加您的构建步骤，例如安装依赖、构建项目等

     - name: Deploy to server
       uses: appleboy/ssh-action@master
    
       with:
          host: ${{secrets.address_HOST}}
          username: root
          key: ${{secrets.address_key}}
          port: 22
          script: |
            cd /root/1/
            node hello.js
